version: 2

builds:
  - id: manager
    main: .
    binary: manager
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags: [-s -w]
  - id: demo-product
    main: ./cmd/demo-product
    binary: demo-product
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags: [-s -w]

archives:
  - formats: [tar.gz]

dockers:
  - id: linux-amd64
    ids: [manager, demo-product]
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    image_templates: ["ghcr.io/devantler-tech/data-product-controller:{{ .Tag }}-amd64"]
    build_flag_templates: ["--platform=linux/amd64"]
  - id: linux-arm64
    ids: [manager, demo-product]
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    image_templates: ["ghcr.io/devantler-tech/data-product-controller:{{ .Tag }}-arm64"]
    build_flag_templates: ["--platform=linux/arm64"]

docker_manifests:
  - name_template: "ghcr.io/devantler-tech/data-product-controller:{{ .Tag }}"
    image_templates:
      - "ghcr.io/devantler-tech/data-product-controller:{{ .Tag }}-amd64"
      - "ghcr.io/devantler-tech/data-product-controller:{{ .Tag }}-arm64"

changelog:
  use: github
