apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-product-controller.fullname" . }}
  labels:
    {{- include "data-product-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: data-product-controller
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: data-product-controller
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: {{ include "data-product-controller.fullname" . }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: controller
          image: {{ include "data-product-controller.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [/manager]
          args: [--leader-elect]
          env:
            - name: REGISTRY_UI_ENABLED
              value: {{ .Values.registryUI.enabled | quote }}
          ports:
            - name: registry
              containerPort: 8082
            - name: health
              containerPort: 8081
            - name: metrics
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
