apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-product-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    checkov.io/skip1: CKV_K8S_21=Helm installs this resource into the tested release namespace.
  labels:
    {{- include "data-product-controller.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: data-product-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: 80
      targetPort: registry
