{{- if .Values.demoProduct.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-product-controller.fullname" . }}-harbour
  labels:
    {{- include "data-product-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: harbour-product
spec:
  replicas: {{ .Values.demoProduct.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: data-product-controller
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: harbour-product
  template:
    metadata:
      labels:
        app.kubernetes.io/name: data-product-controller
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: harbour-product
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: product
          image: {{ include "data-product-controller.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [/demo-product]
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true
          resources:
            {{- toYaml .Values.demoProduct.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-product-controller.fullname" . }}-harbour
  labels:
    {{- include "data-product-controller.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: data-product-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: harbour-product
  ports:
    - name: http
      port: 80
      targetPort: http
{{- end }}
