apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "data-product-controller.fullname" . }}
  labels:
    {{- include "data-product-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [data.devantler.tech]
    resources: [dataproducts]
    verbs: [get, list, watch]
  - apiGroups: [data.devantler.tech]
    resources: [dataproducts/status]
    verbs: [get, patch, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "data-product-controller.fullname" . }}
  labels:
    {{- include "data-product-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "data-product-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "data-product-controller.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "data-product-controller.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-product-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "data-product-controller.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-product-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "data-product-controller.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "data-product-controller.fullname" . }}
    namespace: {{ .Release.Namespace }}
