apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "data-product-controller.fullname" . }}
  labels:
    {{- include "data-product-controller.labels" . | nindent 4 }}
automountServiceAccountToken: true
