//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSecretReference) DeepCopyInto(out *ConnectionSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSecretReference.
func (in *ConnectionSecretReference) DeepCopy() *ConnectionSecretReference {
	if in == nil {
		return nil
	}
	out := new(ConnectionSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProduct) DeepCopyInto(out *DataProduct) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProduct.
func (in *DataProduct) DeepCopy() *DataProduct {
	if in == nil {
		return nil
	}
	out := new(DataProduct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataProduct) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProductList) DeepCopyInto(out *DataProductList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataProduct, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProductList.
func (in *DataProductList) DeepCopy() *DataProductList {
	if in == nil {
		return nil
	}
	out := new(DataProductList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataProductList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProductSpec) DeepCopyInto(out *DataProductSpec) {
	*out = *in
	out.Owner = in.Owner
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]InputPort, len(*in))
		copy(*out, *in)
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]OutputPort, len(*in))
		copy(*out, *in)
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(ProductUI)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(ProvisionedSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProductSpec.
func (in *DataProductSpec) DeepCopy() *DataProductSpec {
	if in == nil {
		return nil
	}
	out := new(DataProductSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataProductStatus) DeepCopyInto(out *DataProductStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataProductStatus.
func (in *DataProductStatus) DeepCopy() *DataProductStatus {
	if in == nil {
		return nil
	}
	out := new(DataProductStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputPort) DeepCopyInto(out *InputPort) {
	*out = *in
	out.ProductRef = in.ProductRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputPort.
func (in *InputPort) DeepCopy() *InputPort {
	if in == nil {
		return nil
	}
	out := new(InputPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutputPort) DeepCopyInto(out *OutputPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutputPort.
func (in *OutputPort) DeepCopy() *OutputPort {
	if in == nil {
		return nil
	}
	out := new(OutputPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductOwner) DeepCopyInto(out *ProductOwner) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductOwner.
func (in *ProductOwner) DeepCopy() *ProductOwner {
	if in == nil {
		return nil
	}
	out := new(ProductOwner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductReference) DeepCopyInto(out *ProductReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductReference.
func (in *ProductReference) DeepCopy() *ProductReference {
	if in == nil {
		return nil
	}
	out := new(ProductReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductUI) DeepCopyInto(out *ProductUI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductUI.
func (in *ProductUI) DeepCopy() *ProductUI {
	if in == nil {
		return nil
	}
	out := new(ProductUI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionedResourceReference) DeepCopyInto(out *ProvisionedResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionedResourceReference.
func (in *ProvisionedResourceReference) DeepCopy() *ProvisionedResourceReference {
	if in == nil {
		return nil
	}
	out := new(ProvisionedResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionedSource) DeepCopyInto(out *ProvisionedSource) {
	*out = *in
	out.ResourceRef = in.ResourceRef
	out.ConnectionSecretRef = in.ConnectionSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionedSource.
func (in *ProvisionedSource) DeepCopy() *ProvisionedSource {
	if in == nil {
		return nil
	}
	out := new(ProvisionedSource)
	in.DeepCopyInto(out)
	return out
}
